### ISSUE TITLE
(macOS Catalina) Cocoa port can't open any files

### ISSUE THREAD

**Issue by Dmac9244** [LIJI32/SameBoy#263]
When running the program, every filetype (.gb, .gbc...) that SameBoy should be able to run was greyed out on the file select screen, and when I tried right-clicking to open one of these files in SameBoy, my computer gave me an error along the lines of "SameBoy can't run files with this extension: [the extension of the file I was trying to run]."

I was able to hack around the first problem by editing Info.plist so that SameBoy could open any file, so I could develop locally on my computer, but this needs a proper fix so it works properly in release versions.

The hack was to replace the contents of CFBundleTypeExtensions under Item 0 under Document Types with "*", and to delete the other file type identifiers under Item 0, effectively telling it it could open any file. I also deleted the other items, since with this first item SameBoy could open the others anyway. 

I'm running on macOS Catalina 10.15.5, and the issue doesn't happen on Mojave.

**Comment by LIJI32** [comment]
This is a known bug with macOS's file association that also affects mGBA. mGBA and SameBoy's association definition conflicts with Visual Boy Advance's in a way that you can't have both VBA and SameBoy or mGBA installed at the same time – either VBA won't be able to open files, or SameBoy/mGBA won't. Unless VBA lines up with mGBA's and SameBoy's definition, or Apple fixes this bug, the only solution is to remove VBA (Or modify its associations). (cc @endrift in case another solution appeared since last time we discussed this bug)

**Comment by LIJI32** [comment]
(Keep in mind that changing this in SameBoy's side will break mGBA, and I prefer breaking VBA and not mGBA if I must break *something*)

**Comment by stijnfrishert** [comment]
So, how does one reset this? I had VBA on my system. Deleted it, restarted macOS, but still can't open .gb files.

**Comment by LIJI32** [comment]
Running this from the terminal should fix it:

```/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain u -domain s -domain l -v```

**Comment by stijnfrishert** [comment]
Yeap, did the trick :)

**Comment by don-raph** [comment]
I'm encountering the same issue, however I don't have VBA installed (never had), and strangely mGBA isn't affected in any way. Running the above lsregister command did help for a short time, however a few hours later file associations are broken again.

**Comment by LIJI32** [comment]
@don-raph Which version of SameBoy are you using? Version 0.16.1 and newer should be able to "peacefully co-exist" with other emulators by working around this bug. If you're using the latest version, try right clicking a GB or GBC file and see what applications appear under the "Open With" submenu, one of the apps in there could be interfering with SameBoy.

**Comment by don-raph** [comment]
@LIJI32 I'm on version 0.16.6. Just in case, I've tried completely deleting Same Boy (including the associated files in the ~/Library folder) and installing a fresh copy, but it still wont recognize the files:

<img width="655" alt="Screenshot 2024-08-26 at 7 59 34 AM" src="https://github.com/user-attachments/assets/888950c7-0762-46f9-9a55-d61e9b84e50c">

Is it possible that it's incompatible with RetroArch? The ".gb" and ".gbc" extensions are currently associated with mGBA on my machine, however if I manually change them to open with Same Boy, I'm getting this error:

<img width="261" alt="Screenshot 2024-08-26 at 8 06 48 AM" src="https://github.com/user-attachments/assets/d63607fd-906f-4a57-8fa0-0ea0839f1360">

**Comment by LIJI32** [comment]
This is really weird, can you list the exact versions of both mGBA and RetroArch you have installed? SameBoy is most likely conflicting with at least one of them. Also, try running the following command in the terminal, and let me know what it outputs:
`mdls /Path/To/Some/rom.gb | grep kMDItemContentType`

**Comment by endrift** [comment]
If there's anything I need to fix in mGBA, please let me know.

**Comment by don-raph** [comment]
mGBA - 0.11-8500-ecfdff233 (latest dev version)
RetroArch - 1.19.1

**Comment by don-raph** [comment]
@LIJI32 I've updated to version 0.16.7 and the issue appears to be resolved on my machine. Thank you!
